### ISSUE TITLE
Missing Guest OS Type freeBSD11-64

### ISSUE THREAD

**Issue by berney** [josenk/terraform-provider-esxi#31]
The `freeBSD11-64` Guest OS Type is missing. VMware is happy with the VM I have created, which is used as a template, and try to cloned by terraform with this plugin.

```
Error: Error applying plan:

1 error(s) occurred:

* module.esxi0.esxi_guest.pfsense: 1 error(s) occurred:

* esxi_guest.pfsense: Error: invalid guestos.  see https://github.com/josenk/vagrant-vmware-esxi/wiki/VMware-ESXi-6.5-guestOS-types                                                                               

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

[user@work terraform]$ grep -i freebsd -r .
./terraform.tfstate:                            "guestos": "freeBSD11-64",
./terraform.tfstate.backup:                            "guestos": "freeBSD11-64",
```

**Comment by josenk** [comment]
Sure...  I'll add them to the next release.

**Comment by josenk** [comment]
fixed in v1.4.1
>https://github.com/josenk/terraform-provider-esxi/releases/tag/1.4.1

**Comment by berney** [comment]
I have tested this and confirmed its not working properly. If my `.terraform/` directory has been blown away, but `terraform.tfstate` and `terraform.tfstate.backup` still exist and the VM is powered off, but desired state is powered on I get the `* esxi_guest.pfsense: Error: invalid guestos.  see https://github.com/josenk/vagrant-vmware-esxi/wiki/VMware-ESXi-6.5-guestOS-types` error still. This is with v1.4.1 of this provider.

I noticed the case is different, `freeBSD11-64` in tfstate vs `freebsd11-64` in source. I think the string comparisons are case sensitive. I had tried replace the string in tfstate, but tfstate is gathered dynamically from ESXi.

If `.terraform/` is empty and `terraform.tfstate` (and backup) are deleted, and VM is off it will successfully deploy it (turns it on).

I think some code paths are doing the validation and some are not.

**Comment by josenk** [comment]
To refresh the tfstate, just run "terraform refresh", it will fix the tfstate with the current running state.
$ terraform refresh 

I'm not really sure how you got upper case in the tfstate, but that doesn't seem correct to me.   I've only seen lower case guestos types...   

    Can you explain how you created the VM from your original post.  "VMware is happy with the VM I have created, which is used as a template".   How was it built?  Using the web gui, vSphere, a clone, etc???   Did you manually edit the vmx file on the host esxi to use upper case?

**Comment by berney** [comment]
VM is built using packer, which has `guest_os_type: freeBSD11-64`. IIRC I had selected "FreeBSD 11 (64-bit)" in the drop down, and saw what value it had and then used that in my packer template.

The ESXi server I'm using had some old pfSense VMs still on it, but I'm using a new install of terraform and your plugin.

In the past, when I first created the packer template, using your terraform-provider-esxi, was happy with these VMs, its only now I noticed the issue. I think the validation should do a case-insensitive comparison because packer and ESXi both don't care, only terraform-provider-esxi cares, and fails when the operation could succeed if ignored the case.

**Comment by josenk** [comment]
Yes, I agree that the validate should be case-insensitive...    I did some tests and see that esxi doesn't really care.   I'll rework the guestos validation in the next release so these types of problems won't creep up any longer.

**Comment by josenk** [comment]
Should be fixed in 1.4.2

**Comment by berney** [comment]
Thanks, I'll do some testing and update if everything is now working properly.
